### ISSUE TITLE
Loosen the dependency versions

### ISSUE THREAD

**Issue by phoffer** [harness/ff-ruby-server-sdk#32]
We are running into issues with dependencies being locked at specific versions. It would be nice if the version dependencies could be pessimistic locked to the minor versions, especially since some of the versions are a couple years old. I have tried to get the tests running locally, but get infinite loops with the node dependencies/generation stuff. So here is what I would hope for in the gem spec:

```
  spec.add_dependency "rufus-scheduler", "~> 3.8"
  spec.add_dependency "libcache", "0.4.2"
  spec.add_dependency "jwt", "~> 2.3"
  spec.add_dependency "moneta", "~> 1.4"

  spec.add_dependency "rest-client", "~> 2.1"

  spec.add_dependency "concurrent-ruby", "~> 1.1"

  spec.add_dependency "murmurhash3", "~> 0.1.6"
```

Thanks!

**Comment by andybharness** [comment]
Thanks for raising this,
We've just released version 1.2.0 which now includes this

**Comment by phoffer** [comment]
Thanks for the update @andybharness. One thing though-- the changes for the `1.2.0` release are to the `Gemfile`, which is for local dev, but not the gemspec, which is what manages the dependency tree when bundling into an app. Could that please get updated as well?

**Comment by andybharness** [comment]
@phoffer my apologies - yes I can update that -hopefully before the end of the week

**Comment by phoffer** [comment]
awesome thank you @andybharness!
